language: rust
rust:
  - stable
jobs:
  include:
    - stage: test
      script: cd project_booking_backend && cargo test
      script: cd project_booking_backend/todo && cargo test
    - stage: build
      script: cd project_booking_cli && cargo build --release      
 
