before_script: cd project_booking_cli
language: rust
rust:
  - stable
jobs:
  include:
    - stage: test
      script: cd project_booking_backend
      script: cargo test --verbose
      script: cd project_booking_backend/todo
      script: cargo test --verbose
    - stage: build
      script: cd project_booking_cli
      script: cargo build --release
