language: rust
rust:
  - stable
cache: cargo  
jobs:
  include:
    - stage: test
      script: 
        - cd project_booking_backend && cargo test
        - cd project_booking_backend/todo && cargo test
    - stage: build
      script: cd project_booking_cli && cargo build --release      
 
