language: rust
rust:
  - stable
cache:
  - rustc
  - rustup
  - cargo
jobs:
  include:
    - stage: test backend
      script: 
        - cd project_booking_backend && RUST_TEST_THREADS=1 cargo test
        - cd todo && RUST_TEST_THREADS=1 cargo test
        - cd project_booking_cli && RUST_TEST_THREADS=1 cargo test
    - stage: test cli
      script: cd project_booking_cli && RUST_TEST_THREADS=1 cargo test
    - stage: build
      script: cd project_booking_cli && cargo build --release      
 
