[package]
name = "project_booking_backend"
version = "0.1.0"
authors = ["Viorel Bota <botaviorel@gmail.com>"]

[dependencies]
todo = { path = "todo" }
logger = { path = "logger" }
formaters = { path = "formaters" }