[package]
name = "todo"
version = "0.1.4"
authors = ["Viorel Bota <botaviorel@gmail.com>"]

[dependencies]
identifiers = { path = "../identifiers" }
task = { path = "../task" }
formaters = { path = "../formaters" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
