[package]
name = "task"
version = "0.1.4"
authors = ["Viorel Bota <botaviorel@gmail.com>"]

[dependencies]
search = { path = "../search" }
formaters = { path = "../formaters" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"