[package]
name = "report"
version = "0.1.2"
authors = ["Viorel Bota <botaviorel@gmail.com>"]

[dependencies]
task = { path = "../task" }
todo = { path = "../todo" }
formaters = { path = "../formaters" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"